# Generated by Django 4.2.1 on 2023-06-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='price_with_discount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
