# Generated by Django 4.2.2 on 2023-06-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_slideritem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideritem',
            name='link',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
