# Generated by Django 4.2.2 on 2023-06-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_slideritem_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideritem',
            name='link',
        ),
    ]
